apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whoami-allow-ingress
  namespace: sre
spec:
  podSelector:
    matchLabels:
      app: whoami
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
