apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: whoami-rules
spec:
  groups:
  - name: whoami.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate on whoami service"
