name: Deploy to K3s Cluster

on:
  push:
    branches:
      - main
      - fideonpartner-publish
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ~/.kube/config

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verificar conexão com cluster
        run: kubectl cluster-info

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/base/ --validate=false
          kubectl apply -f k8s/security/ --validate=false
          kubectl apply -f k8s/monitoring/prometheus-namespace.yaml --validate=false
          kubectl apply -f k8s/monitoring/prometheus-rbac.yaml --validate=false
          kubectl apply -f k8s/monitoring/prometheus-config.yaml --validate=false
          kubectl apply -f k8s/monitoring/prometheus-deployment.yaml --validate=false
          kubectl apply -f k8s/monitoring/prometheus-service.yaml --validate=false
          kubectl apply -f k8s/monitoring/grafana-deployment.yaml --validate=false
          kubectl apply -f k8s/monitoring/grafana-service.yaml --validate=false

      - name: Install Loki with Helm
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm upgrade --install loki grafana/loki-stack --namespace monitoring -f k8s/monitoring/loki-helm-values.yaml

      - name: Install Jaeger with Helm
        run: |
          helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
          helm repo update
          helm install jaeger jaegertracing/jaeger --namespace monitoring -f k8s/monitoring/jaeger-helm-values.yaml
