name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
    - name: Apply manifests
      run: kubectl apply -f k8s/base/
